Feat/post likes2
camilocoelhogomes/projeto_11_linkr pull request #13
Opened 2021-09-18 17:43 UTC by PMafra

Likes and Dislikes working fine with great response time.

2021-09-18 18:18 UTC, andeaquino reviewed
Pra mim o código tá show, só encontrei esses dois pontos

2021-09-18 18:18 UTC, andeaquino commented on src/components/Post.js
> +                                : (`Curtido por ${userInfo.user.username}, ${likes[likes.length - 1]["user.username"]} e outras ${likes.length - 2} pessoa(s)`))))}>
Acredito que em vez do nome do usuário é para aparecer 'Você' na descrição dos likes

2021-09-18 18:18 UTC, andeaquino commented on src/pages/timeLine/TimeLine.js
> +                            posts.map(post => <Post key={post.id} post={post} userInfo={userInfo} getPosts={getPosts}/>)
Há quatro outras páginas(myposts, likedposts, hashtagposts, userposts) que usam o componente Post e precisam dessa atualização.

2021-09-18 18:20 UTC, leonardo-otero390 requested changes
Acho que é de outra parte, mas não estou conseguindo acessar as rotas hashtag e likes

2021-09-18 18:20 UTC, leonardo-otero390 commented on src/components/Post.js
> +    console.log(userInfo);
Não é bom levar console.log para produção

2021-09-18 18:27 UTC, PMafra commented on src/components/Post.js
> +    console.log(userInfo);
Ih, nem tinha visto

2021-09-18 18:45 UTC, merged

2021-09-20 21:59 UTC, leonardo-otero390 commented on src/components/Post.js
> +                                : (`Curtido por ${userInfo.user.username}, ${likes[likes.length - 1]["user.username"]} e outras ${likes.length - 2} pessoa(s)`))))}>
feito