Feat/background img
camilocoelhogomes/projeto_11_linkr pull request #23
Opened 2021-09-20 22:42 UTC by camilocoelhogomes

When the post don't have a img, will appear a picture of Bart sympson with a pen in his ear

2021-09-20 23:16 UTC, andeaquino approved these changes

2021-09-21 12:11 UTC, leonardo-otero390 requested changes
Ficou muito bom, só esse onde comentei que acho que ficaria melhor, recomendo usar o [Gato não encontrado](https://http.cat/404)

2021-09-21 12:11 UTC, leonardo-otero390 commented on src/components/Post.js
> +                                <img alt='link' className='link-img' src={linkImage} />
Acredito que seja isso, perceba que quando não carrega a imagem ainda aparece a logo do link quebrado, tente mudar o src da imagem

2021-09-21 12:15 UTC, camilocoelhogomes commented on src/components/Post.js
> +                                <img alt='link' className='link-img' src={linkImage} />
Alterações realizadas

2021-09-21 12:34 UTC, leonardo-otero390 commented on src/components/Post.js
> +                                <img alt='link' className='link-img' src={linkImage} />
Perfeito!

2021-09-21 12:35 UTC, leonardo-otero390 approved these changes

2021-09-21 12:45 UTC, andeaquino approved these changes

2021-09-21 12:46 UTC, merged