Feat/follow unfollow
camilocoelhogomes/projeto_11_linkr pull request #29
Opened 2021-09-21 19:18 UTC by PMafra

2021-09-21 19:37 UTC, leonardo-otero390 approved these changes
Show!

2021-09-21 19:52 UTC, andeaquino requested changes
Estou conseguindo seguir, mas eu n consigo dar unfollow em nenhum usuário. É só comigo?

2021-09-21 19:55 UTC, camilocoelhogomes requested changes
Ficou ótimo, só alteraria a lógica do posicionamento do botão na página, para que seja definido na header  e não no próprio botão

2021-09-21 19:55 UTC, camilocoelhogomes commented on src/pages/userPosts/UserPosts.js
> +                    <SmallAlert errorMessage={errorMessage} top={"40px"} left={"calc(100% - 200px)"}></SmallAlert>
Não seria melhor definir um widt pra header, colocar ela com display flex e space between, ao invés do position left e top? acho que assim ficaria mais fácil de dar manutenção depois

2021-09-21 21:25 UTC, PMafra commented on src/pages/userPosts/UserPosts.js
> +                    <SmallAlert errorMessage={errorMessage} top={"40px"} left={"calc(100% - 200px)"}></SmallAlert>
Não entendi Camilo. A Header já está com display flex e space between. O position left e top é para o alerta de erro, que também é usado para os likes/dislikes em outra posição da página, e por isso precisa de props dessa forma

2021-09-21 21:26 UTC, PMafra commented on src/pages/userPosts/UserPosts.js
> +                    <SmallAlert errorMessage={errorMessage} top={"40px"} left={"calc(100% - 200px)"}></SmallAlert>
E o botão também está dentro da Header

2021-09-21 21:29 UTC, PMafra commented
> Estou conseguindo seguir, mas eu n consigo dar unfollow em nenhum usuário. É só comigo?

Concertei aqui Anderson. Estava fazendo testes enviando o token errado e esqueci de colocar de volta.

2021-09-21 21:39 UTC, camilocoelhogomes commented on src/pages/userPosts/UserPosts.js
> +                    <SmallAlert errorMessage={errorMessage} top={"40px"} left={"calc(100% - 200px)"}></SmallAlert>
É pq eu não entendi a nescessidade de definir esse top e essse left dentro do small alert na mão, tipo se eu quisesse usar ele outro ponto da página, ele poderia ficar relativo ao componente pai, saca? tipo, se eu quiser usar esse mesmo alert nos posts. Qualquer duvida me chama no slack

2021-09-21 21:50 UTC, PMafra commented on src/pages/userPosts/UserPosts.js
> +                    <SmallAlert errorMessage={errorMessage} top={"40px"} left={"calc(100% - 200px)"}></SmallAlert>
Minha ideia no caso é por que ele está com z-index: 5 e assim poderia ficar na frente ou em cima de qualquer coisa, já que é uma box de alert.Pq se eu tirar, se quisermos manter o box de alert dos likes por exemplo, vamos ter que arranjar alguma lugar dentro dos posts pra colocar ele, e mudar o layout pra caber a box de alert

2021-09-21 21:51 UTC, PMafra commented on src/pages/userPosts/UserPosts.js
> +                    <SmallAlert errorMessage={errorMessage} top={"40px"} left={"calc(100% - 200px)"}></SmallAlert>
Se quiser chama discord q agnt conversa

2021-09-21 21:52 UTC, PMafra commented on src/pages/userPosts/UserPosts.js
> +                    <SmallAlert errorMessage={errorMessage} top={"40px"} left={"calc(100% - 200px)"}></SmallAlert>
No caso o SmallAlert já esta sendo usado nos posts para o like e dislike

2021-09-21 21:53 UTC, PMafra commented on src/pages/userPosts/UserPosts.js
> +                    <SmallAlert errorMessage={errorMessage} top={"40px"} left={"calc(100% - 200px)"}></SmallAlert>
![image](https://user-images.githubusercontent.com/84607762/134252931-a35f7f76-9af0-415a-9462-279df2d819f3.png)

2021-09-21 21:55 UTC, PMafra commented on src/pages/userPosts/UserPosts.js
> +                    <SmallAlert errorMessage={errorMessage} top={"40px"} left={"calc(100% - 200px)"}></SmallAlert>
Esse é também o Small Alert, e a posição dele está definida com top e left pois ele não pode ficar dentro de nenhuma div, pq iria alterar o layout. É esse o motivo das props de top e left estarem sendo passadas.

2021-09-21 22:00 UTC, camilocoelhogomes commented on src/pages/userPosts/UserPosts.js
> +                    <SmallAlert errorMessage={errorMessage} top={"40px"} left={"calc(100% - 200px)"}></SmallAlert>
Ah se é o mesmo, então ta ok, fica top assim mesmo

2021-09-21 22:01 UTC, camilocoelhogomes approved these changes
Só resolver os problemas de merge, e por mim pode dar merge

2021-09-21 22:03 UTC, PMafra commented on src/pages/userPosts/UserPosts.js
> +                    <SmallAlert errorMessage={errorMessage} top={"40px"} left={"calc(100% - 200px)"}></SmallAlert>
Ah, nao sei se é isso, mas o SmallAlert tem também um position absolute, entao sempre vai ficar com a posição relativa ao componente pai que vc colcoar ele dentro

2021-09-21 22:06 UTC, andeaquino approved these changes
Pra mim tá show!

2021-09-21 22:10 UTC, PMafra commented on src/pages/userPosts/UserPosts.js
> +                    <SmallAlert errorMessage={errorMessage} top={"40px"} left={"calc(100% - 200px)"}></SmallAlert>
Ah show, não tinha visto seu comentário

2021-09-21 23:09 UTC, andeaquino requested changes
Tirando esse detalhe, acredito que tá tudo em ordem

2021-09-21 23:09 UTC, andeaquino commented on src/pages/shared/styled-components/PageContainer.js
> +        gap: 13px;
Não era pra ter esse gap aqui

2021-09-22 10:29 UTC, camilocoelhogomes approved these changes
Pronto pra  merge!

2021-09-22 16:06 UTC, merged