Feat/post comments
camilocoelhogomes/projeto_11_linkr pull request #30
Opened 2021-09-22 16:40 UTC by andeaquino

Posts are displaying comments and logged user is now able to comment.

2021-09-22 20:28 UTC, camilocoelhogomes requested changes
Anderson, muito top o código, é mais uma questão de funcionalidade mesmo, no meu ele mandou comentário vazio ao eu apertar enter, ai ficou lá como se fosse um comentário mais sem texto algum, acho que seria legal colocar essa validação antes de enviar um comentário

2021-09-22 20:44 UTC, andeaquino commented
> Anderson, muito top o código, é mais uma questão de funcionalidade mesmo, no meu ele mandou comentário vazio ao eu apertar enter, ai ficou lá como se fosse um comentário mais sem texto algum, acho que seria legal colocar essa validação antes de enviar um comentário

Boa, aparentemente o servidor aceita comentários sem texto, mas realmente não faz muito sentido, vou fazer aqui

2021-09-22 22:00 UTC, camilocoelhogomes approved these changes
Agora sim ta top!

2021-09-23 11:16 UTC, PMafra approved these changes
Top!

2021-09-23 11:17 UTC, merged