Feat/search users
camilocoelhogomes/projeto_11_linkr pull request #35
Opened 2021-09-23 14:59 UTC by leonardo-otero390

Search user input done

2021-09-23 19:33 UTC, camilocoelhogomes approved these changes
Ficou tóp! só esperando merge

2021-09-23 19:58 UTC, andeaquino requested changes
O código acredito q tá show, mas o botão de follow mudou de posição e tá criando um scroll lateral quando entra na página de um user. E n seria melhor a pesquisa resetar qnd o usuário clicar numa opção?

2021-09-24 20:16 UTC, camilocoelhogomes approved these changes
Por mim por dar merge

2021-09-25 14:33 UTC, PMafra approved these changes

2021-09-25 15:33 UTC, andeaquino approved these changes

2021-09-25 15:53 UTC, merged