Fix/key posts
camilocoelhogomes/projeto_11_linkr pull request #36
Opened 2021-09-23 22:42 UTC by andeaquino

Posts receiving appropriate keys. When deleting or re-posting the page doesnt need to reload anymore.

2021-09-23 23:40 UTC, leonardo-otero390 approved these changes

2021-09-23 23:40 UTC, leonardo-otero390 commented on src/pages/hashtagPosts/HashtagPosts.js
> +                            posts.map(post => <Post key={!!post.repostId ? post.repostId : post.id} post={post} userInfo={userInfo} getPosts={getPosts} />)
Por que não usar o index do map?

2021-09-23 23:52 UTC, camilocoelhogomes commented on src/pages/hashtagPosts/HashtagPosts.js
> +                            posts.map(post => <Post key={!!post.repostId ? post.repostId : post.id} post={post} userInfo={userInfo} getPosts={getPosts} />)
Foi justamente isso que deu o problema de renderização, pelo que eu entendi, como o index do map não é unico, pq alterava os posts e tudo mais e as posições, ai o react ficava confuso na hora de renderizar, mas quando usa o post id funciona bem, tem uma conversa lá no slack que a Bruna explica melhor

2021-09-23 23:56 UTC, camilocoelhogomes requested changes
Não sei se é algo da documentação, mas quando pesquisa as #tags não aparece os re-posts

2021-09-24 10:51 UTC, andeaquino commented
> Não sei se é algo da documentação, mas quando pesquisa as #tags não aparece os re-posts

Isso, tanto os posts das # qnt dos likes o servidor não manda re-posts

2021-09-24 11:47 UTC, merged